version: '3.1'

services:

  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pg12345
      POSTGRES_USER: liya
      POSTGRES_DB: wb
    ports:
      - "5333:5432"

  nats:
    image: nats-streaming
    restart: always
    ports:
      - "4222:4222"
      - "8223:8223"